# Generated by Django 3.0.2 on 2020-01-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparshkalp', '0002_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='description',
        ),
    ]
