# Generated by Django 3.0.2 on 2020-01-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparshkalp', '0003_remove_upload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
