# Generated by Django 3.0.2 on 2020-01-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparshkalp', '0004_upload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='doctorId',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
